### ISSUE TITLE
[Question] QCA7005 chip firmware and Pib file

### ISSUE THREAD

**Issue by mcagriaksoy** [uhi22/ccs32clara#28]
Hello, In the software side I haven`t seen any PIB file operations like reading. Are you flashing the PIB once, via open-plc-tools?

I am curious about also, QCA7005 chip firmware, are you using the version 1.2.5?

**Comment by uhi22** [comment]
Hi, the PIB and the QCA7005 firmware are both contained in the image of the SPI flash. This just a 1:1 copy of an OEM charge control unit. So we neither did any firmware updates nor PIB writing via open-plc-tools. But nevertheless, the use of open-plc-tools should work if the QCAs SPI is connected to a raspberry and the STM is hold in reset. Never done this.

The process how to bring the PIB and firmware into the SPI flash is described here: https://github.com/uhi22/foccci#programming-the-spi-flash
