### ISSUE TITLE
AC Charging Lock requests interferes with Timed Locking

### ISSUE THREAD

**Issue by Tom-evnut** [uhi22/ccs32clara#35]
When running 0,0 thresholds to enable timed locking pushing multiple requests creates a resetting timer.

Proposed Solution: check if timer is set, do not reset if its running.

**Comment by Tom-evnut** [comment]
https://github.com/uhi22/ccs32clara/pull/36

Created Pull to attempt to fix this.

**Comment by uhi22** [comment]
Thanks, merged the PR.
