### ISSUE TITLE
EVSEPresentVoltage during WeldingDetection implausibly decoded in some cases

### ISSUE THREAD

**Issue by uhi22** [uhi22/ccs32clara#9]
In 2024-01-19_clara_numbat_lightbulb_verydark.claralog.decoded.txt:
[89570] In state WaitForWeldingDetectionRes
EVSEPresentVoltage 1078427648V
while the charger reports a "normal" value:
"EVSEPresentVoltage.Multiplier": "0",
"EVSEPresentVoltage.Value": "47",
"EVSEPresentVoltage.Unit": "V",

**Comment by jsphuebner** [comment]
@uhi22 
If you want to print numbers with decimal point just convert them to s32fp e.g. with FP_FROMFLT

**Comment by uhi22** [comment]
EVSEPresentVoltage is correctly decoded now. Tested on various chargers. --> Close.
